[package]
name = "tokio-stomp"
version = "0.1.0"
description = "Asynchronous streaming STOMP client"
authors = ["Alex Whitney <adwhit@fastmail.com>"]
repository = "http://github.com/adwhit/tokio-stomp"
homepage = "http://github.com/adwhit/tokio-stomp"
keywords = ["stomp", "tokio", "streaming"]
license = "MIT"
readme = "README.md"

[dependencies]
nom = "4.0.0-alpha2"
failure = "0.1.1"
bytes = "0.4.6"
futures = "0.1.18"
tokio-io = "0.1.4"
tokio = "0.1.0"
