[package]
name = "tokio-stomp"
version = "0.1.0"
description = "Asynchronous streaming STOMP client"
authors = ["Alex Whitney <adwhit@fastmail.com>"]
repository = "http://github.com/adwhit/tokio-stomp"
homepage = "http://github.com/adwhit/tokio-stomp"
keywords = ["stomp", "tokio", "streaming"]
license = "MIT"
readme = "README.md"
edition = "2018"

[dependencies]
nom = "4.2.3"
failure = "0.1.5"
bytes = "0.4.12"
futures = "0.1"
tokio = "0.1.20"
