[package]
name = "tokio-stomp"
version = "0.1.0"
authors = ["Alex Whitney <adwhit@fastmail.com>"]

[dependencies]
nom = "4.0.0-alpha2"
failure = "0.1.1"
bytes = "0.4.6"
futures = "0.1.18"
tokio-io = "0.1.4"
tokio = "0.1.0"
